[workspace]
resolver = "2"
members = [
    "file_transfer_template",
    "file_transfer_template_worker_api",
    "file_transfer_template_worker",
    "download",
    "list_files"
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
